### ISSUE TITLE
Copy MongoDB to MySQL loader into preprocessor?

### ISSUE THREAD

**Issue by chewisinho** [BIDS-projects/etl#7]
Instead of merging in the pull request, let's consider using Alex's code as a reference and copying it (with modifications) into preprocessor.py.

Currently, preprocessor.py reads from MongoDB, writes to MongoDB (parsed), and Alex's script reads from the parsed MongoDB and writes to MySQL. It would be more streamlined if the preprocessor just reads from MongoDB and writes to MySQL directly.

Similarly, the matrix file (read from MySQL into Python matrix) should probably go in the aggregator/visualizer.

We can consider the pull request to be more like useful code that should be ported elsewhere. Anyone else have thoughts?

See #6

**Comment by alvinwan** [comment]
Merging might make it easier to spot diffs, but either works.

The matrix might not even be need in the visualization server-side. In theory the JS on client-side could benefit from it, but I think we can leave that job to `d3.js`. The matrix seems nifty though, perhaps for another form of analysis down the line.

**Comment by chewisinho** [comment]
It's currently on a branch, so we can just compare the branches.

As for the matrix, then, maybe we can merge it into the aggregator repo.

**Comment by alvinwan** [comment]
Yeah, I can look at the matrix separately.

**Comment by chewisinho** [comment]
This is currently complete.
